config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "/calculator", to: "tip_calculation#new", as: :calculator_new
  get "/dashboard", to: "tip_calculation#index", as: :calculator_index
  post "/calculations", to: "tip_calculation#create", as: :calculator_create
  get "/calculations/:id", to: "tip_calculation#show", as: :calculator_show
  get "/calculations/:id/edit", to: "tip_calculation#edit", as: :calculator_edit
  patch "/calculations/:id", to: "tip_calculation#update", as: :calculator_update
  delete "/calculations/:id", to: "tip_calculation#destroy", as: :calculator_destroy
  
  match '*unmatched', to: 'application#route_not_found', via: :all

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tip_calculation.rb
class TipCalculation < ApplicationRecord
    validates :bill_amount, :tip_percentage, :num_people, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :tip_percentage, numericality: { in: 0..100 }
    validates :num_people, numericality: { greater_than: 0 }

    before_save :calculate_derived_attributes

    private

    def calculate_derived_attributes
        self.tip_amount = (bill_amount * tip_percentage) / 100
        self.total_bill = bill_amount + tip_amount
        self.per_person_amount = total_bill / num_people
        self.timestamp ||= Time.current
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  def index
    @tip_calculations = TipCalculation.all
  end

  def route_not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found', status: :not_found }
      format.json { render json: { error: "Not Found" }, status: :not_found }
      format.any { head :not_found }
    end
  end
end

app/controllers/tip_calculation_controller.rb
class TipCalculationController < ApplicationController
    before_action :set_tip_calculation, only: [:show, :edit, :update, :destroy]

    def index
        @tip_calculations = TipCalculation.all
    end

    def new
        @tip_calculation = TipCalculation.new
    end

    def edit
    end

    def show
    end

    def create
        @tip_calculation = TipCalculation.new(tip_calculation_params)

        if @tip_calculation.save
            redirect_to calculator_show_path(@tip_calculation)
        else
            render :new
        end
    end

    def update
        @tip_calculation.assign_attributes(tip_calculation_params)

        if @tip_calculation.save
            redirect_to calculator_show_path(@tip_calculation)
        else
            render :edit
        end
    end

    def destroy
        @tip_calculation.destroy
        redirect_to calculator_index_path
    end

    def set_tip_calculation
        @tip_calculation = TipCalculation.find_by(id: params[:id])
    end

    private

    def tip_calculation_params
        params.require(:tip_calculation).permit(:bill_amount, :tip_percentage, :num_people)
    end
end

app/controllers/tip_calculations_controller.rb
class TipCalculationsController < ApplicationController
  before_action :set_tip_calculation, only: %i[ show edit update destroy ]

  # GET /tip_calculations or /tip_calculations.json
  def index
    @tip_calculations = TipCalculation.all
  end

  # GET /tip_calculations/1 or /tip_calculations/1.json
  def show
  end

  # GET /tip_calculations/new
  def new
    @tip_calculation = TipCalculation.new
  end

  # GET /tip_calculations/1/edit
  def edit
  end

  # POST /tip_calculations or /tip_calculations.json
  def create
    bill_amount = tip_calculation_params[:bill_amount].to_f
    tip_percentage = tip_calculation_params[:tip_percentage].to_f
    num_people = tip_calculation_params[:num_people].to_i

    tip_amount = (bill_amount * tip_percentage) / 100
    total_bill = bill_amount + tip_amount
    per_person_amount = total_bill / num_people

    @tip_calculation = TipCalculation.new(
      bill_amount: bill_amount,
      tip_percentage: tip_percentage,
      tip_amount: tip_amount,
      total_bill: total_bill,
      num_people: num_people,
      per_person_amount: per_person_amount,
      timestamp: Time.current
    )

    respond_to do |format|
      if @tip_calculation.save
        format.html { redirect_to @tip_calculation, notice: "Tip calculation was successfully created." }
        format.json { render :show, status: :created, location: @tip_calculation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tip_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tip_calculations/1 or /tip_calculations/1.json
  def update
    bill_amount = tip_calculation_params[:bill_amount].to_f
    tip_percentage = tip_calculation_params[:tip_percentage].to_f
    num_people = tip_calculation_params[:num_people].to_i
  
    tip_amount = (bill_amount * tip_percentage) / 100
    total_bill = bill_amount + tip_amount
    per_person_amount = total_bill / num_people
  
    @tip_calculation.assign_attributes(
      bill_amount: bill_amount,
      tip_percentage: tip_percentage,
      tip_amount: tip_amount,
      total_bill: total_bill,
      num_people: num_people,
      per_person_amount: per_person_amount
    )

    respond_to do |format|
      if @tip_calculation.save
        format.html { redirect_to @tip_calculation, notice: "Tip calculation was successfully updated." }
        format.json { render :show, status: :ok, location: @tip_calculation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tip_calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tip_calculations/1 or /tip_calculations/1.json
  def destroy
    @tip_calculation.destroy!

    respond_to do |format|
      format.html { redirect_to tip_calculations_path, status: :see_other, notice: "Tip calculation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip_calculation
      @tip_calculation = TipCalculation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tip_calculation_params
      params.require(:tip_calculation).permit(:bill_amount, :tip_percentage, :num_people)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tip_calculation_helper.rb
module TipCalculationHelper
end

app/helpers/tip_calculations_helper.rb
module TipCalculationsHelper
end

app/views/application/index.html.erb
<div class="container mt-4">
  <h1>Tip Calculation Records</h1>
  <div class="mb-2">
    <%= link_to 'Create', calculator_new_path, class: 'btn btn-success' %>
  </div>
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Bill Amount</th>
        <th>Tip Percentage</th>
        <th>Tip Amount</th>
        <th>Total Bill</th>
        <th>Number of People</th>
        <th>Per Person Amount</th>
        <th>Timestamp</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% if @tip_calculations.present? %>
      <% @tip_calculations.each do |calculation| %>
        <tr>
          <td>$<%= calculation.bill_amount %></td>
          <td><%= calculation.tip_percentage %>%</td>
          <td>$<%= calculation.tip_amount %></td>
          <td>$<%= calculation.total_bill %></td>
          <td><%= calculation.num_people %></td>
          <td>$<%= calculation.per_person_amount %></td>
          <td><%= calculation.timestamp.strftime('%d-%m-%Y %H:%M') %></td>
          <td>
            <%= link_to 'View', calculator_show_path(calculation), class: 'btn btn-primary' %>
          </td>
        </tr>
      <% end %>
    <% else %>
        <tr>
          <td colspan="100%" class="text-center">No Records Found.</td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= content_for(:title) || "Tip Calculator" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container min-90vh">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white navbar-dark text-center text-lg-start">
    <div class="text-center p-3">
        © 2024 Designed by:
        <%= link_to "Dominic", "https://www.ematembu.com", class:"text-white" %>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <%= link_to "Tip Calculator", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Dashboard", calculator_index_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Home", root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Create", calculator_new_path, class:"nav-link" %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Sign up', root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Login', root_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Logout', root_path, method: :delete, class:"nav-link" %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/tip_calculation/_form.html.erb
<div class="card">
  <div class="card-body">
    <% if flash[:error] || alert %>
      <div class="alert alert-danger"><%= [flash[:error], alert].compact.join('<br>') %></div>
    <% end %>

    <%= form_with(model: @tip_calculation, url: @tip_calculation.new_record? ? calculator_create_path : calculator_update_path(@tip_calculation), method: @tip_calculation.new_record? ? :post : :patch, local: true) do |form| %>
      <div class="mb-3">
        <%= form.label :bill_amount, "Bill Amount ($)", class: "form-label" %>
        <%= form.number_field :bill_amount, step: 0.01, min: 0, required: true, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :tip_percentage, "Tip Percentage (%)" , class: "form-label"%>
        <%= form.number_field :tip_percentage, step: 1, min: 0, max: 100, required: true, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :num_people, "Number of People", class: "form-label" %>
        <%= form.number_field :num_people, min: 1, required: true, class: "form-control" %>
      </div>

      <%= form.submit @tip_calculation.new_record? ? "Calculate Tip" : "Update Record", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tip_calculation/edit.html.erb
<h1 class="mb-4">Edit Tip Record</h1>
<div class="mb-2">
  <%= link_to 'Back to HomePage', root_path, class: 'btn btn-secondary' %>
</div>
<%= render partial: 'form' %>

app/views/tip_calculation/index.html.erb
<div class="container mt-4">
  <h1>Tip Calculation Records</h1>
  <div class="mb-2">
    <%= link_to 'Create', calculator_new_path, class: 'btn btn-success' %>
  </div>
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Bill Amount</th>
        <th>Tip Percentage</th>
        <th>Tip Amount</th>
        <th>Total Bill</th>
        <th>Number of People</th>
        <th>Per Person Amount</th>
        <th>Timestamp</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% if @tip_calculations.present? %>
      <% @tip_calculations.each do |calculation| %>
        <tr>
          <td>$<%= calculation.bill_amount %></td>
          <td><%= calculation.tip_percentage %>%</td>
          <td>$<%= calculation.tip_amount %></td>
          <td>$<%= calculation.total_bill %></td>
          <td><%= calculation.num_people %></td>
          <td>$<%= calculation.per_person_amount %></td>
          <td><%= calculation.timestamp.strftime('%d-%m-%Y %H:%M') %></td>
          <td class="d-flex">
            <%= link_to 'View', calculator_show_path(calculation), class: 'btn btn-success' %>
            <%= link_to 'Edit', calculator_edit_path(calculation), class: 'btn btn-primary' %>
            <%= form_with url: calculator_destroy_path(calculation), method: :delete, data: { confirm: 'Are you sure?' }, local: true do %>
              <%= submit_tag 'Delete', class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
        <tr>
          <td colspan="100%" class="text-center">No Records Found.</td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tip_calculation/new.html.erb
<h1 class="mb-4">Tip Calculator</h1>
<div class="mb-2">
  <%= link_to 'Back to HomePage', root_path, class: 'btn btn-secondary' %>
</div>
<%= render partial: 'form' %>

app/views/tip_calculation/show.html.erb
<div class="card">
  <div class="card-header">
    <h2>Tip Calculation Result</h2>
  </div>
    <div class="card-body">
      <% if @tip_calculation %>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <strong>Bill Amount:</strong> $<%= @tip_calculation.bill_amount %>
        </li>
        <li class="list-group-item">
          <strong>Tip Percentage:</strong> <%= @tip_calculation.tip_percentage %>%
        </li>
        <li class="list-group-item">
          <strong>Tip Amount:</strong> $<%= @tip_calculation.tip_amount %>
        </li>
        <li class="list-group-item">
          <strong>Total Bill:</strong> $<%= @tip_calculation.total_bill %>
        </li>
        <li class="list-group-item">
          <strong>Per Person Amount:</strong> $<%= @tip_calculation.per_person_amount %>
        </li>
        <li class="list-group-item">
          <strong>Number of People:</strong> <%= @tip_calculation.num_people %>
        </li>
      </ul>
      <% else %>
        <p class="text-center">Record not found</p>
      <% end %>
    </div>
  <div class="card-footer d-flex justify-content-between">
    <%= link_to "Edit", calculator_edit_path(@tip_calculation), class: "btn btn-primary" %>
    <%= link_to 'Back to HomePage', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/tip_calculations/_form.html.erb
<div class="container mt-4">
  <%= form_with(model: tip_calculation) do |form| %>
    <% if tip_calculation.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(tip_calculation.errors.count, "error") %> prohibited this tip calculation from being saved:</h4>
        <ul>
          <% tip_calculation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :bill_amount, class: "form-label" %>
      <%= form.number_field :bill_amount, class: "form-control", required: true, min: 0 %>
    </div>

    <div class="mb-3">
      <%= form.label :tip_percentage, class: "form-label" %>
      <%= form.number_field :tip_percentage, class: "form-control", min: 0, max: 100 %>
    </div>

    <div class="mb-3">
      <%= form.label :num_people, class: "form-label" %>
      <%= form.number_field :num_people, class: "form-control", required: true, min: 1 %>
    </div>

    <div class="d-flex justify-content-end">
      <%= form.submit "Calculate Tip", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tip_calculations/_tip_calculation.html.erb
<div class="card" id="<%= dom_id tip_calculation %>">
  <div class="card-body">
    <h5 class="card-title">Tip Calculation Details</h5>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong>Bill Amount:</strong> <%= tip_calculation.bill_amount %>
      </li>
      <li class="list-group-item">
        <strong>Tip Percentage:</strong> <%= tip_calculation.tip_percentage %>%
      </li>
      <li class="list-group-item">
        <strong>Tip Amount:</strong> <%= tip_calculation.tip_amount %>
      </li>
      <li class="list-group-item">
        <strong>Total Bill:</strong> <%= tip_calculation.total_bill %>
      </li>
      <li class="list-group-item">
        <strong>Number of People:</strong> <%= tip_calculation.num_people %>
      </li>
      <li class="list-group-item">
        <strong>Per Person Amount:</strong> <%= tip_calculation.per_person_amount %>
      </li>
      <li class="list-group-item">
        <strong>Timestamp:</strong> <%= tip_calculation.timestamp %>
      </li>
    </ul>
  </div>
</div>

app/views/tip_calculations/edit.html.erb
<% content_for :title, "Editing Tip Calculation" %>

<div class="container mt-4">
  <h1 class="mb-4">Editing Tip Calculation</h1>

  <%= render "form", tip_calculation: @tip_calculation %>

  <div class="mt-4">
    <%= link_to "View Tip Calculation", @tip_calculation, class: "btn btn-secondary" %>
    <%= link_to "Back to Tip Calculations", tip_calculations_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/tip_calculations/index.html.erb
<div class="container mt-4">
  <% if notice.present? %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>

  <% content_for :title, "Tip Calculations" %>

  <h1 class="mb-4">Tip Calculations</h1>

  <div id="tip_calculations" class="row">
    <% @tip_calculations.each do |tip_calculation| %>
      <div class="col-md-4 mb-4">
        <%= render tip_calculation %>
        <p>
          <%= link_to "View", tip_calculation, class: "btn btn-secondary" %>
        </p>
      </div>
    <% end %>
  </div>

  <%= link_to "New Tip Calculation", new_tip_calculation_path, class: "btn btn-primary" %>
</div>

app/views/tip_calculations/new.html.erb
<div class="container mt-4">
  <% content_for :title, "New Tip Calculation" %>

  <h1 class="mb-4">New Tip Calculation</h1>

  <%= render "form", tip_calculation: @tip_calculation %>

  <div class="mt-4">
    <%= link_to "Back to Tip Calculations", tip_calculations_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/tip_calculations/show.html.erb
<div class="container mt-4">
  <% if notice.present? %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>

  <%= render @tip_calculation %>

  <div class="mt-4">
    <%= link_to "Edit", edit_tip_calculation_path(@tip_calculation), class: "btn btn-secondary" %>
    <%= link_to "Back", tip_calculations_path, class: "btn btn-primary" %>

    <%= button_to "Delete", @tip_calculation, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
  </div>
</div>